on: [push]
jobs:
 deploy:
   runs-on: [ubuntu-latest]
   steps:
     - run: |
         curl --request POST --url http://localhost:3000/update \
         --header "Content-Type: application/json" \
         --data '{"pass": "adfs"}'
    
